### ISSUE TITLE
Server endpoint : Managing friends and user fuzzy search

### ISSUE THREAD

**Issue by mattsmithies** [blockmason/lndr#10]
GET /username
?snippet={username_fragment}

Fuzzy search for user with common username snippet.

When searching for a friend in the 'Add a new friend' dialog.

**Comment by mattsmithies** [comment]
POST request to /friend_request

- Related friend from the fuzzy search of above, are we using address as id?
- Include pending status of friend in friend array of user.
- Upon confirm/deny of given request update status if successful or remove friend from list.
- Send push notification to user, alert and update app state.

Perhaps we could have a email submitted for users that aren't registered, send email to a prospect and keep on list.

**Comment by mattsmithies** [comment]
PUT /friend
?id={friend_id}&nickname={cheese}

Are we using a  server side session or a generated API access key?

Allow the user to update a friends data inside of their friends array.

**Comment by aupiff** [comment]
I was thinking generated API access key.

**Comment by timgalebach** [comment]
Oh there's actually a cleaner way: the user wanting to change his name just
signs the tx changing it.

**Comment by aupiff** [comment]
We could do that. Though all API endpoints should be restricted to certain authenticated users (those who have signed into the app) and I'm not sure if all txs should be signed.

Additionally, if you submit a request to change your nickname with no nonce, the same request can be repeated in the future to change the name again (data is the same, thus sig is the same). When a signature scheme is used, it is important that all messages be unique. It might be best to avoid a nonce scheme to make this name change functionality possible via signed requests.

**Comment by aupiff** [comment]
@timgalebach nevermind, you're right. We'll use UTC timestamp as a nonce.

**Comment by mattsmithies** [comment]
POST /user

New registered user after account creation

**Comment by aupiff** [comment]
fuzzy search implemented in branch `feature-fuzzy-nick-search`
