### ISSUE TITLE
Add upload/download profile picture to AWS S3

### ISSUE THREAD

**Issue by willbach** [blockmason/lndr#109]
This can be done by either having the server upload the images or by sending specific credentials to the client

**Comment by aupiff** [comment]
What endpoints do we need?

**Comment by aupiff** [comment]
/profile_photo/{address} REQ BODY Base64-encoded jpeg.

**Comment by willbach** [comment]
POST /profile_photo
REQ BODY:

{ data: {base 64-endcoded jpeg}
, signature: {sig}
}

GET /profile_photo/{user address}
Response: base64 encoded string of the picture

**Comment by aupiff** [comment]
Endpoint added in #116.
