### ISSUE TITLE
Push notification service options

### ISSUE THREAD

**Issue by mattsmithies** [blockmason/lndr#11]
**Firebase** - https://firebase.google.com/docs/cloud-messaging/

Positives 
- Opportunity for additional firebase features and cloud functions
- Well documented, examples/tutorials

Negatives:
- Some data collection, they check before usage

Links:
https://medium.com/@tewolfe2/push-notifications-with-react-native-ios-and-firebase-cloud-messaging-fcm-6492b7326b53
https://github.com/evollu/react-native-fcm
https://codeburst.io/react-native-push-notifications-with-firebase-1f23c4f0af65

**Urban airship** - https://www.urbanairship.com/products/mobile-app-engagement/pricing

Positives 
- Feature rich
- Mature
- Well documented, examples/tutorials

Negatives
- Expensive
- Probably overkill for requirements.

Links:
https://docs.urbanairship.com/whats-new/2017-05-17-new-framework-react-native/
https://docs.urbanairship.com/platform/react-native/
https://npm.runkit.com/react-native-ua

**OneSignal** - https://onesignal.com/

Positives: 
- Well documented
- API driven
- Lots of docs for platforms
- Lots of momentum

Negatives:
- Concerns of data usage. See here:
https://www.bountysource.com/issues/43499832-research-onesignal-com-privacy-implications

Cost: FREE, although they sell the data of the pushes to advertisers.

We can pay for privacy and opting out but we need to contact them directly.

Links:
https://github.com/geektimecoil/react-native-onesignal
https://medium.com/differential/react-native-push-notifications-with-onesignal-9db6a7d75e1e
https://documentation.onesignal.com/v3.0/reference

**Parse Platform & Back4App**

Price: https://www.back4app.com/pricing 

Main:
http://docs.parseplatform.org/parse-server/guide/#push-notifications
https://www.back4app.com/

Brief setup: 

```
> var server = new ParseServer({
>   databaseURI: '...',
>   cloud: '...',
>   appId: '...',
>   masterKey: '...',
>   push: {
>     android: {
>       senderId: '...',
>       apiKey: '...'
>     },
>     ios: {
>       pfx: '/file/path/to/XXX.p12',
>       passphrase: '', // optional password to your p12/PFX
>       bundleId: '',
>       production: false
>     },
>     osx: {
>       pfx: '/file/path/to/XXX.p12',
>       passphrase: '', // optional password to your p12/PFX
>       bundleId: '',
>       production: false
>     },
>     tvos: {
>       pfx: '/file/path/to/XXX.p12',
>       passphrase: '', // optional password to your p12/PFX
>       bundleId: '',
>       production: false
>     }
>   }
> : '...',
>   cloud: '...',
>   appId: '...',
>   masterKey: '...',
>   push: {
>     android: {
>       senderId: '...',
>       apiKey: '...'
>     },
>     ios: {
>       pfx: '/file/path/to/XXX.p12',
>       passphrase: '', // optional password to your p12/PFX
>       bundleId: '',
>       production: false
>     },
>     osx: {
>       pfx: '/file/path/to/XXX.p12',
>       passphrase: '', // optional password to your p12/PFX
>       bundleId: '',
>       production: false
>     },
>     tvos: {
>       pfx: '/file/path/to/XXX.p12',
>       passphrase: '', // optional password to your p12/PFX
>       bundleId: '',
>       production: false
>     }
> });
```

Once set it uses a curl interface to send pushes to channels.

Example:

```
> curl -X POST \
>   -H "X-Parse-Application-Id: you_app_id" \
>   -H "X-Parse-Master-Key: your_master_key" \
>   -H "Content-Type: application/json" \
>   -d '{
>         "where": {
>           "deviceType": {
>             "$in": [
>               "ios",
>               "android"
>             ]
>           }
>         },
>         "data": {
>           "title": "The Shining",
>           "alert": "All work and no play makes Jack a dull boy."
>         }
>       }'\   http://your_server_address/parse/push
```

This service provide a hosted parse solution, although they have been known to edit their pricing structure.
https://docs.back4app.com/

In my previous engagements we used back4app then migrated to a self hosted mongo parse server.

RN:
https://github.com/parse-community/Parse-SDK-JS
http://docs.parseplatform.org/js/guide/

We need to generate keys for iOS and Android, need to add extra snippets into the respective native projects, the appdelegate and  manifest.

Lib:
https://github.com/wix/react-native-notifications <-- preferred
Or
https://github.com/zo0r/react-native-push-notification

**Comment by aupiff** [comment]
We've gone with Urban Airship.
