### ISSUE TITLE
Record total $ or ETH amount of settlements and transfers for each user

### ISSUE THREAD

**Issue by willbach** [blockmason/lndr#128]
The DB should store the Eth value of settlements and transfers per user.

Proposed Architecture: GET to /eth_transfers/:userAddress returns a JSON with a list of objects. Each object has the keys "amount", "type" ('settlement' or 'transfer'), "user", and "date" (created date)

POST to /eth_transfers sends an object with keys "amount", "type" ('settlement' or 'transfer'), and "user".

This structure avoids the need to modify existing settlement code and can be used for both kinds of ETH transfer within Lndr

**Comment by aupiff** [comment]
I should have asked earlier, why do we need this if we're just a recording layer?

**Comment by aupiff** [comment]
We'll query etherscan API when accounts are unlocked and update on transfers and settlements.

http://api.etherscan.io/api?module=account&action=txlist&address=0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae&startblock=0&sort=asc&apikey=YourApiKeyToken

The /config endpoint will include a blocknumber that represents a block that was mined approx. one week ago. The key will be "weekAgoBlock".

**Comment by aupiff** [comment]
/config endpoint now has "weekAgoBlock" on `master`
