### ISSUE TITLE
improve scheme for selecting tx to resubmit

### ISSUE THREAD

**Issue by aupiff** [blockmason/lndr#61]
Currently using amount as a unique id -- I made this silly on purpose. I wanted to think of a good scheme as quickly as possible.

**Comment by timgalebach** [comment]
Just hash everything unique about the tx?

**Comment by aupiff** [comment]
Yeah, I was considering some other schemes based on tx index (age of tx) because I was telling the server to resubmit records using curl from my machine and I didn't want to be calculate hashes. This was a temporary hack to just get things working. I want to use the CreditRecord hash which serves as the primary key in the `verified_credits` db table. I just have to make the server include the hash in its `/unsubmitted_transactions` response so that clients have an easy time using the api.

**Comment by aupiff** [comment]
fixed in #63

**Comment by aupiff** [comment]
good stack exchange post on resubmission:

https://ethereum.stackexchange.com/questions/16269/geth-transactions-stuck-in-pending-resend-fails
