### ISSUE TITLE
Send push notification when transaction is pending

### ISSUE THREAD

**Issue by willbach** [blockmason/lndr#66]

**Comment by aupiff** [comment]
To do this, I assume all I need to do is send the following payload to UA's `POST /api/push` endpoint. @TheAznShumai, do I have this right?

```
{
    "audience": {
        "android_channel": "31279004-103e-4ba8-b4bf-65eb3eb81859"
    },
   "notification": {
      "alert": "new pending credit from {friend name}",
      "actions": {
          "app_defined": { "LNDR_ACTIONS" : ["NEW_PENDING"] }
       }
   },
   "device_types" : "all"
}
```

**Comment by TheAznShumai** [comment]
you may need to specify the device type and the channel depending on the platform, but this is correct.

**Comment by timgalebach** [comment]
Are we currently storing device type and channel on the server? Just want
to get this cleaned up quickly.

**Comment by aupiff** [comment]
@timgalebach there are "platform" and "channelID" fields associated with a LNDR address that are set using the `/register_push` endpoint.

**Comment by aupiff** [comment]
@TheAznShumai FYI, I'm limiting `platform` values to "ios" and "android".

**Comment by timgalebach** [comment]
Unacceptable. The TimPhone 2000 is right around the corner.

**Comment by aupiff** [comment]
If there's an urban airship account for blockmason, please share the account credentials with me. This is probably the easiest way.

**Comment by timgalebach** [comment]
shared

On Dec 20, 2017 2:29 PM, "Roy Blankman" <notifications@github.com> wrote:

If there's an urban airship account for blockmason, please share the
accounts credentials with me. This is probably the easiest way.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/blockmason/lndr/issues/66#issuecomment-353158828>, or mute
the thread

**Comment by aupiff** [comment]
Ok, I have a PR out with rough version of push notifications implemented. I still need to test what I have so far. @TheAznShumai does the mobile application currently hit the server's `/register_push` endpoint? I assume this would happen when an account is created. Can we can get that functionality into a new release of the iPhone and Android app?

(We'll probably have to support multiple devices per user. I mentioned this in another comment somewhere a few days ago. We should put off implementing this until basic notifications are working but let's keep it in the back of our heads.)

**Comment by aupiff** [comment]
I've updated the production server. For users with a channelID & platform associated with their account, the server will attempt to hit the urban airship /push endpoint whenever a new pending record is created or a pending record is confirmed.

**Comment by timgalebach** [comment]
Do we want to do it for cancelled records too?

**Comment by aupiff** [comment]
Yeah we do, I'm going to add that in an upcoming PR. The /reject endpoint is one I wanted to refactor so I put it off.

**Comment by aupiff** [comment]
code has been tested and is currently live on production server.
