### ISSUE TITLE
create server endpoint that accepts signed credit record

### ISSUE THREAD

**Issue by aupiff** [blockmason/lndr#9]
Currently there is only one `/submit` endpoint that accepts `CreditRecord Unsigned`. Another endpoint should be created at `/submit-signed` that accepts `CreditRecord Signed`.

**Comment by timgalebach** [comment]
What's the purpose of accepting Unsigned CreditRecords?

**Comment by aupiff** [comment]
1) for testing, since the CLI & mobile are unable to sign CreditRecords
2) to allow a centralized service to authenticate users via login and free them of the burden of maintaining their own privkeys

We could delete this feature if (2) doesn't seem valuable.

**Comment by aupiff** [comment]
Done.
